### ISSUE TITLE
VMD Store

### ISSUE THREAD

**Issue by maojinyuan** [BioSIM-Research-Group/vmdStore#1]
Hi,
I'm here. Thanks a lot for your help.

The problem of my failure to open VMDware is that it was always loading, I didn't know if my computer has a problem?
![aaa](https://user-images.githubusercontent.com/20769696/64249993-928f4000-cf47-11e9-80b4-d4e432e524c3.png)

BTW, I do the examples as the introduction of molUP, and I get the Gaussian input file and execute it, however, it was repored "MM function not complete" as below, I found the undefined bondstretch and angle bend were exactly the positions of cutten amino acid residues, I wonder this parameters can be added manually or can be added automatically in your package(molUP)?
cause I didn't find some related tutorial to avoid this problem.

>  Include all MM classes
>  Bondstretch undefined between atoms   1209   1211 C-H [H,L]
>  Bondstretch undefined between atoms   2174   2176 C-H [H,L]
>  Bondstretch undefined between atoms   3074   3076 C-H [H,L]
>  Bondstretch undefined between atoms   3864   3866 C-H [H,L]
>  Angle bend  undefined between atoms   1202   1209   1211 CT-C-H [H,H,L]
>  Angle bend  undefined between atoms   1210   1209   1211 O-C-H [H,H,L]
>  Angle bend  undefined between atoms   2167   2174   2176 CT-C-H [H,H,L]
>  Angle bend  undefined between atoms   2175   2174   2176 O-C-H [H,H,L]
>  Angle bend  undefined between atoms   3066   3074   3076 CT-C-H [H,H,L]
>  Angle bend  undefined between atoms   3075   3074   3076 O-C-H [H,H,L]
>  Angle bend  undefined between atoms   3851   3864   3866 CT-C-H [H,H,L]
>  Angle bend  undefined between atoms   3865   3864   3866 O-C-H [H,H,L]
>  MM function not complete
>  Error termination via Lnk1e in /share/apps/g16.b01/g16/l120.exe at Wed Sep  4 19:21:11 2019.

**Comment by henriquefer** [comment]
Regarding the VMD Store, can you please show me the content of the "/share/home/maojy/vmd1.9.4a35/vmdStore/vmdStore.rc" file. 

---

molUP does not automatically provide additional parameters.
When the layers are split between atoms with hydrogens bonded, you have no problem because Gaussian will use the available parameters. 
For example, consider the following molecule. 
```
  H H
  | |
H-C-C-H
  | |
  H H
```
If you split the system in two-layer through the C-C bond, Gaussian will not comply about missing parameters because the link-atom is an H and the parameters for that type of bond and angles already exist.

However, if your molecule is something like:
```
  H F
  | |
H-C-C-Cl
  | |
  H Br
```

Considering the same two-layer system, the second C does not have parameters for the C-H bond required by the link-atom addition. In this case, you have to provide suitable parameters for the link-atoms.

I hope that this helps you understand the procedure.

In your particular case, you have to identify the atom type of heavy those (e.g. 1209) and add a line on your parameters section:
```
HrmStr1 CT H 340.00 1.0900
```
where 340.0 is the force constant and 1.0900 is the equilibrium value.

This also applies to angles bends:
```
HrmBnd1  C  N  H  50.00 120.0001
```

**Comment by maojinyuan** [comment]
This is the content of vmdStore in "/share/home/maojy/vmd1.9.4a35/vmdStore/vmdStore.rc" :
[vmdStore.txt](https://github.com/BioSIM-Research-Group/vmdStore/files/3574624/vmdStore.txt)

> ####vmdStore#### START vmdStore
> ## Version 1.1.11
> variable vmdStorePath "/share/home/maojy/vmd1.9.4a35/vmdStore"
> lappend auto_path $::vmdStorePath
> vmd_install_extension vmdStore "vmdStore::start" "VMD Store/VMD Store"
> ####vmdStore#### END vmdStore
> ## VMD Store Plugin Manager ##
> ## Please, do not change this file unless you know what are you doing! ##

Thank you very much for your help, I'll try the way.    0..0

**Comment by henriquefer** [comment]
Apparently, the file is okay.

Let me know some other details:
1. Do you have an internet connection active when you start the VMD Store?
2. Send the full VMD output (terminal) after starting VMD Store.

Best regards

**Comment by maojinyuan** [comment]
Absolutely yes, I am talking to u by Internet. however, I am in China, I wonder if the firewall shield the connect, I have no idea？
Unfortunately，the output in terminal didn't go on, like the picture:
![aaa](https://user-images.githubusercontent.com/20769696/64261259-d0e42980-cf5e-11e9-9fd4-8c4bbd719c5a.png)

**Comment by henriquefer** [comment]
Okay. VMD Store only communicates with GitHub, so I suppose that it is not firewall related since you can access GitHub. 
In fact, the output does not provide any output...

You told me in the other post, that you are running Centos, but this seems to be Windows. Can you confirm the operating system?

**Comment by maojinyuan** [comment]
I am sorry to reply you so late.
Actually, the VMDStore both in Windows and Linux are not work, the picture I uploaded in last answer is the Linux system, I just control it by Xshell.

**Comment by henriquefer** [comment]
Since we have no idea about the error and before deepening, please remove the vmdStore directory and all the related-lines in the .vmdrc/vmd.rc file. Then, install the VMD Store following tutorial 1. for Window) and 3. for Linux: https://biosim.pt/how-to-install-vmd-store/

**Comment by maojinyuan** [comment]
Hi, 
There are some thing I should report to u.
I attempt to open the VMDStore in Linux without any changes and it works recent days, but it seem to unstable sometimes, I mean, this time I can load the VMDStore, next time maybe not.

**Comment by henriquefer** [comment]
Hi,
It seems that you are experiencing some kind of instability when the VMD Store tries to communicate with GitHub. 
I will try to replicate that behavior to try to understand the cause.

**Comment by Pharmaoie** [comment]
Hi @henriquefer 

I am experiencing the same issue with VMDstore not loading. 

Here is the error I get when I try to open VMDstore from the extension. 

<img width="664" alt="VMD" src="https://user-images.githubusercontent.com/48831900/224344739-0743a572-4016-478f-9eac-572122130ad2.png">


Here is the error message: 

invalid command name "styleConfig"
invalid command name "styleConfig"
    while executing
"styleConfig ."
    (procedure "setThemeDefaults" line 12)
    invoked from within
"setThemeDefaults "
    (procedure "tablelist::handleThemeChangedEvent" line 45)
    invoked from within
"tablelist::handleThemeChangedEvent"
    ("after" script)


If I choose to skip messages, I get the loading window, and it doesn't go beyond that. 

<img width="940" alt="image" src="https://user-images.githubusercontent.com/48831900/224345787-9bee8c43-d9d9-415f-a255-c801d5326b28.png">

Thanks in advance! 
-MoSorour

**Comment by Ranabirju15** [comment]
I am also experiencing the same problem. vmdStore stuck in Loading. I installed vmdStore with VMD for LINUXAMD64, version 1.9.3 in Linux mint OS.

**Comment by zlohlab** [comment]
Hi, 
I was wondering if there was any progress regarding the above issue, as I have installed the VmdStore today on Ubuntu and getting stuck at the same stage. There are no error messages, but the vmdstore windows indicates that new data is being collected from the internet (same window  shown as in the other previous posts).
Thank you very much.
Mire
