### ISSUE TITLE
plugin.zip

### ISSUE THREAD

**Issue by september-cell** [BioSIM-Research-Group/vmdStore#3]
vmdStore/temp/plugin.zip.ZIP.
unzip:  cannot find or open /Users/user/Applications/vmdStore/temp/plugin.zip, /Users/katy/Applications/vmdStore/temp/plugin.zip.zip or /Users/user/Applications/vmdStore/temp/plugin.zip.ZIP.
    while executing
"exec unzip -q -o "$::vmdStorePath/temp/plugin.zip" -d "$::vmdStorePath/temp""
    (procedure "vmdStore::installPlugin" line 54)
    invoked from within
"vmdStore::installPlugin $vmdStore::installLink"
    invoked from within

**Comment by henriquefer** [comment]
Hello.
Can you provide further details on how are you trying to install VMD Store?
OS:
VMD Store Installation method:
VMD version:

Thank you

**Comment by september-cell** [comment]
OS: BigSur 11.2.2
VMD Store Installation method: through vmd Store
VMD version: 1.9.4a51

**Comment by henriquefer** [comment]
Hello,
Can you please try to install VMD Store using the Tk console method: https://github.com/BioSIM-Research-Group/vmdStore#installation
Video instructions here: https://www.youtube.com/watch?v=r6Ci2AS2uv0

Let me know if it helps.

Thank you

**Comment by september-cell** [comment]
Installing with the Tk console did not change the error message about the plugin. The error is the same.

**Comment by henriquefer** [comment]
I just tested it on macOS 11.2.2 and VMD 1.9.4a51, and everything is working on my machine. Can you send a print of the installation prompt with the correct path and another one with the error message?
Thank you

**Comment by september-cell** [comment]
Can you share the plugin file? It's the file I'm missing

**Comment by henriquefer** [comment]
You can download the VMD Store here: https://github.com/BioSIM-Research-Group/vmdStore/releases/tag/1.1.11
Please, follow the manual installation tutorial: https://github.com/BioSIM-Research-Group/vmdStore#manual-installation

Let me know if it works for you.
Thank you

**Comment by september-cell** [comment]
It did not, because I still don't have plugin.zip, can you please point me to that file?

**Comment by september-cell** [comment]
unzip:  cannot find or open /Users/me/Desktop/vmdStore/temp/plugin.zip, /Users/me/Desktop/vmdStore/temp/plugin.zip.zip or /Users/me/Desktop/vmdStore/temp/plugin.zip.ZIP.

**Comment by henriquefer** [comment]
Can you clarified if you can already open the VMD Store? I though that you cannot launch VMD Store, but it seems that you cannot install plugins. Can you confirm that please?
Thank you

**Comment by september-cell** [comment]
Yes, I can open the VMD Store, but I can't install anything from the store.

**Comment by henriquefer** [comment]
I am sorry, I misinterpreted the issue.
Please, check if you have access to the GitHub servers for download. To do so, run the following command on Terminal:
wget https://codeload.github.com/BioSIM-Research-Group/vmdMagazine/zip/1.1

This should download a file ("1.1") with 8.6 MB.

Since some users have reported restrictions in the access to some parts of GitHub, let's discard this scenario first. 

Thank you

**Comment by september-cell** [comment]
It's ok
Yes, that command works correctly

**Comment by september-cell** [comment]
Oh...
the issue was i did not have wget,  but 
brew install wget
fixed the molup problem. Thank you for all of your patience!

**Comment by henriquefer** [comment]
My bad. Wget is not under the requirements of VMD Store. I am so sorry.
I am going to include that info in the requirements section.
I am glad that we solve the issue.
Thank you.
