### ISSUE TITLE
unknown option "-background" error

### ISSUE THREAD

**Issue by SuparnaGhosh01** [BioSIM-Research-Group/vmdStore#4]
I am seeing an Error notification when rendering from ToolBox.
System - Windows10.
VMD - 1.9.3.

"unknown option "-background"
unknown option "-background"
    while executing
"$f5.render configure -background red -text "Rendering...""
    (procedure "vmdRender::render" line 5)
    invoked from within
"vmdRender::render"
    invoked from within
".gui.frame5.render invoke ""
![Capture](https://user-images.githubusercontent.com/82993363/115655668-b8609700-a36e-11eb-901a-4f1487f60d81.PNG)

**Comment by henriquefer** [comment]
Hello.
Thank you for letting us know.
I am going to check the possible bug. I let you know ASAP.

**Comment by henriquefer** [comment]
The bug has been fixed. Please, update the toolBar to the version 1.2.1. You can easily update toolBar through VMD Store. 
The toolBar is not perfect yet, so we appreciate your comment on reporting the bug. :)
