### ISSUE TITLE
bad regexp?

### ISSUE THREAD

**Issue by davidhoover** [BioSIM-Research-Group/vmdStore#6]
I was trying to get vmdstore to load in vmd, and it just hung.

I made a modification in vmdstore.tcl that fixed it:

        # Getting the online Version of vmdStore
        set onlineVersion ""
        while {$onlineVersion == ""} {
                set url "https://github.com/BioSIM-Research-Group/vmdStore/releases/latest"
                set token [::http::geturl $url -timeout 1000]
                set data [::http::data $token]
                regexp -all {tag\/(\S+)\"} $data --> onlineVersion
                set onlineVersion "1.1.13"
        }

Is something wrong with the regexp that determines the latest version?

**Comment by davidhoover** [comment]
I wonder if the url "https://github.com/BioSIM-Research-Group/vmdStore/releases/latest" is getting blocked?  Would it be possible to add some kind of error checking or perhaps limit the number of times it loops waiting for a proper onlineVersion value?

**Comment by henriquefer** [comment]
Hello.
Thank you for reporting this issue.
I have released a new version (1.1.14) that should fix this bug.
